library(gridExtra)
library(lattice)
tc <- read.csv("tc1_ex.csv")
p1 <- wireframe(tc$f1 ~ tc$x + tc$y, data=tc, scales=list(draw=F), drape=T, zlab='f(x,y)')
p2 <- wireframe(tc$f2 ~ tc$x + tc$y, data=tc,  scales=list(draw=F), drape=T, zlab='f(x,y)', screen=list(x=-60))
grid.arrange(p1,p2, ncol=2)
p3 <- wireframe(tc$f1 ~ tc$x + tc$y, data=tc,  scales=list(draw=F), drape=T, zlab='f(x,y)', screen=list(y=70,x=-50))
p4 <- wireframe(tc$f2 ~ tc$x + tc$y, data=tc,  scales=list(draw=F), drape=T, zlab='f(x,y)', screen=list(y=70,x=-50))
grid.arrange(p3,p4, ncol=2)
p5 <- wireframe(tc$f1 ~ tc$x + tc$y, data=tc,  scales=list(draw=F), drape=T, zlab='f(x,y)', screen=list(z=-10,x=100,y=-10))
p6 <- wireframe(tc$f2 ~ tc$x + tc$y, data=tc,  scales=list(draw=F), drape=T, zlab='f(x,y)', screen=list(z=-10,x=100,y=-10))
grid.arrange(p5,p6, ncol=2)
p7 <- wireframe(tc$f1 ~ tc$x + tc$y, data=tc,  scales=list(draw=F), drape=T, zlab='f(x,y)', screen=list(z=-10,x=120,y=-10))
p8 <- wireframe(tc$f2 ~ tc$x + tc$y, data=tc,  scales=list(draw=F), drape=T, zlab='f(x,y)', screen=list(z=-10,x=120,y=-10))
grid.arrange(p7,p8, ncol=2)
