//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by APOT6.rc
//
#define IDOK2                           3
#define IDC_BUTTON_SA_APPLY             3
#define IDD_APOT6_DIALOG                102
#define IDR_MAINFRAME                   128
#define IDB_COLOR_SCALE                 131
#define IDD_EA_DIALOG                   132
#define IDD_EDITOR_DIALOG               133
#define IDD_SPLASH_DIALOG               134
#define IDB_SPLASH_BITMAP               136
#define IDD_NEC_DIALOG                  138
#define IDD_HELP_DIALOG                 139
#define IDR_ACCELERATOR1                140
#define IDI_ICON_HELP                   141
#define IDI_ICON_ABOUT                  142
#define IDI_ICON_TREE                   146
#define IDD_SA_DIALOG                   147
#define IDD_HC_DIALOG                   148
#define IDD_ES_DIALOG                   149
#define IDC_OPENGL_VIEW                 1000
#define IDC_PLATFORM                    1002
#define IDC_STATIC_PLATFORM             1003
#define IDC_BUTTON_ANTENNA              1005
#define IDC_EDIT_POPSIZE                1006
#define IDC_EDIT_GENERATIONS            1007
#define IDC_EDIT_EXPWEIGHT              1007
#define IDC_EDIT_MUTATION               1008
#define IDC_LIST_RESULTS                1009
#define IDC_BUTTON_RUN                  1010
#define IDC_LIST_ANTENNA                1011
#define IDC_EDIT_MIN_THETA              1012
#define IDC_EDIT_STEP_THETA             1013
#define IDC_EDIT_MIN_PHI                1014
#define IDC_EDIT_STEP_PHI               1015
#define IDC_EDIT_MIN_FREQ               1016
#define IDC_EDIT_STEP_FREQ              1017
#define IDC_BUTTON_ANTENNA_REMOVE       1018
#define IDC_EDIT_INC_THETA              1019
#define IDC_EDIT_INC_PHI                1020
#define IDC_EDIT_INC_FREQ               1021
#define IDC_BUTTON_NEC                  1022
#define IDC_EDIT_USERNAME               1023
#define IDC_EDIT_PASSWORD               1024
#define IDC_PROGRESS                    1025
#define IDC_CHECK_LOCAL                 1026
#define IDC_THETA_CONTROL               1030
#define IDC_PHI_CONTROL                 1031
#define IDC_STATIC_GA                   1032
#define IDC_STATIC_RESULTS              1033
#define IDC_STATIC_FREQ                 1034
#define IDC_STATIC_PHI                  1035
#define IDC_STATIC_THETA                1036
#define IDC_STATIC_USERNAME             1037
#define IDC_STATIC_PASSWORD             1038
#define IDC_STATIC_POPSIZE              1039
#define IDC_STATIC_GENERATIONS          1040
#define IDC_STATIC_MUTATION             1041
#define IDC_STATIC_F1                   1042
#define IDC_STATIC_F2                   1043
#define IDC_STATIC_F3                   1044
#define IDC_STATIC_T1                   1045
#define IDC_STATIC_T2                   1046
#define IDC_STATIC_T3                   1047
#define IDC_STATIC_P1                   1048
#define IDC_STATIC_P2                   1049
#define IDC_STATIC_P3                   1050
#define IDC_EDIT_GEN                    1054
#define IDC_RADIO_STDGA                 1055
#define IDC_RADIO_ALPSEA                1056
#define IDC_EDIT_TOURSIZE               1057
#define IDC_EDIT_ELITISM                1059
#define IDC_EDIT_LAYERS                 1065
#define IDC_EDIT_LAYERSIZE              1067
#define IDC_COMBO_REPR                  1068
#define IDC_BUTTON_EDIT                 1069
#define IDC_EDIT_SEED                   1069
#define IDC_BUTTON_GENERATE             1070
#define IDC_CHECK_AUTOGEN               1071
#define IDC_BUTTON2                     1072
#define IDC_EDIT_RECOMB                 1074
#define IDC_BUTTON_APPLY                1075
#define IDC_STATIC_STATUS               1078
#define IDC_EDIT_AGEGAP                 1078
#define IDC_BUTTON_LUA                  1079
#define IDC_RADIO1                      1080
#define IDC_RADIO_EXHAUSTIVE            1080
#define IDC_RADIO_SA_SM                 1080
#define IDC_RADIO_ES_SM                 1080
#define IDC_RADIO_HC_SM                 1080
#define IDC_BUTTON_X                    1083
#define IDC_BUTTON_Y                    1084
#define IDC_BUTTON_Z                    1085
#define IDC_BUTTON_X_NEG                1086
#define IDC_BUTTON_Y_NEG                1087
#define IDC_BUTTON_Z_NEG                1088
#define IDC_CHECK_ORTHO                 1089
#define IDC_BUTTON_EDIT_NEC             1090
#define IDC_EDIT_NEC                    1091
#define IDC_BUTTON_ABOUT                1093
#define IDC_EDIT_GS                     1094
#define IDC_COMBO_IPERF                 1095
#define IDC_EDIT_NRADL                  1096
#define IDC_EDIT_EPSR                   1097
#define IDC_EDIT_SIG                    1098
#define IDC_COMBO_ICLIF                 1099
#define IDC_EDIT_EPSR2                  1100
#define IDC_EDIT_SIG2                   1101
#define IDC_EDIT_CLT                    1102
#define IDC_EDIT_CHT                    1103
#define IDC_CHECK_GS                    1104
#define IDC_CHECK_GN                    1105
#define IDC_CHECK_GD                    1106
#define IDC_BUTTON_HELP                 1108
#define IDC_TEXT_HELP                   1111
#define IDC_CHECK_NE                    1112
#define IDC_COMBO_NEAR                  1114
#define IDC_EDIT_NRX                    1115
#define IDC_EDIT_NRY                    1116
#define IDC_EDIT_NRZ                    1117
#define IDC_EDIT_XNR                    1118
#define IDC_EDIT_YNR                    1119
#define IDC_EDIT_ZNR                    1120
#define IDC_CHECK_LE                    1121
#define IDC_COMBO_RSET                  1122
#define IDC_TREE_ANTENNA                1122
#define IDC_EDIT_NPTS                   1123
#define IDC_EDIT_X1                     1124
#define IDC_EDIT_Y1                     1125
#define IDC_LIST_ALGORITHMS             1125
#define IDC_EDIT_Z1                     1126
#define IDC_STATIC_ALGORITHMS           1126
#define IDC_EDIT_X2                     1127
#define IDC_EDIT_SA_ITERATIONS          1127
#define IDC_EDIT_Y2                     1128
#define IDC_EDIT_HC_ITERATIONS          1128
#define IDC_EDIT_Z2                     1129
#define IDC_EDIT_HC_MUTATIONS           1129
#define IDC_EDIT_HC_SEED                1130
#define IDC_EDIT_HC_FREQ                1131
#define IDC_EDIT_HC_CONVERGENCE         1132
#define IDC_EDIT_SA_MUTATIONS           1133
#define IDC_EDIT_HC_GEN_COND            1133
#define IDC_EDIT_SA_SEED                1134
#define IDC_EDIT_HC_FITNESS_COND        1134
#define IDC_EDIT_SA_INITIAL_TEMP        1135
#define IDC_BUTTON_HC_APPLY             1135
#define IDC_EDIT_SA_TEMP_FACTOR         1136
#define IDC_EDIT_HC_EXPWEIGHT           1136
#define IDC_EDIT_SA_ITER_PER_TEMP       1137
#define IDC_EDIT_SA_FREQ                1138
#define IDC_EDIT_SA_CONVERGENCE         1139
#define IDC_EDIT_SA_EXPWEIGHT           1140
#define IDC_EDIT_SA_GEN_COND            1141
#define IDC_BUTTON1                     1141
#define IDC_BUTTON_SAVE_TO_LUA          1141
#define IDC_BUTTON_ES_APPLY             1141
#define IDC_BUTTON_HC_GENERATE          1141
#define IDC_EDIT_SA_FITNESS_COND        1142
#define IDC_EDIT_ES_GENERATIONS         1142
#define IDC_EDIT_ES_MU                  1143
#define IDC_EDIT_ES_LAMBDA              1144
#define IDC_EDIT_ES_MUTATION            1145
#define IDC_EDIT_ES_EXPWEIGHT           1146
#define IDC_CHECK1                      1147
#define IDC_CHECK_ES_AUTOGEN            1147
#define IDC_CHECK_SA_AUTOGEN            1147
#define IDC_CHECK_HC_AUTOGEN            1147
#define IDC_CHECK_GA_LNM                1147
#define IDC_EDIT_ES_SEED                1148
#define IDC_BUTTON_ES_GENERATE          1149
#define IDC_RADIO_GA_SM                 1150
#define IDC_RADIO_GA_NM                 1151
#define IDC_RADIO_SA_NM                 1152
#define IDC_RADIO_ES_NM                 1153
#define IDC_RADIO_HC_NM                 1154
#define IDC_BUTTON_SA_GENERATE          1161
#define IDC_RADIO_SA_LNM                1162
#define IDC_CHECK_SA_LNM                1163
#define IDC_EDIT_SA_LNM                 1164
#define IDC_RADIO_ES_LNM                1165
#define IDC_CHECK_ES_LNM                1166
#define IDC_EDIT_ES_LNM                 1167
#define IDC_RADIO_HC_LNM                1168
#define IDC_CHECK_HC_LNM                1169
#define IDC_EDIT_HC_LNM                 1170
#define IDC_RADIO_GA_LNM                1171
#define IDC_EDIT_GA_LNM                 1172
#define IDC_EDIT_BEST_FITNESS           1173
#define IDC_STATIC_BEST_FITNESS         1174
#define ID_ACCELERATOR_ZOOMIN           32771
#define ID_ACCELERATOR_ZOOMOUT          32773
#define ID_ACCELERATOR_RESET            32774
#define ID_ACCELERATOR_SELECTALL        32775
#define ID_ACCELERATOR_SELECTNONE       32776
#define ID_ACCELERATOR_ORIGINUP         32778
#define ID_ACCELERATOR_ORIGINDOWN       32779
#define ID_ACCELERATOR_ORIGINLEFT       32780
#define ID_ACCELERATOR_ORIGINRIGHT      32781
#define ID_ACCELERATOR_ORIGINRESET      32782
#define ID_ACCELERATOR_WIREFRAME        32783
#define ID_ACCELERATOR_RADUP            32785
#define ID_ACCELERATOR_RADDOWN          32786
#define ID_ACCELERATOR32788             32788
#define ID_ACCELERATOR_UNDO             32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32790
#define _APS_NEXT_CONTROL_VALUE         1175
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
